config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only: [:edit, :update, :show]
end

app/models/user.rb
require 'uri'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :website, allow_blank: true, format: { with: URI::regexp(%w(http https)) }

  has_attached_file :cv
  do_not_validate_attachment_file_type :cv
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_layout

  private

  def set_layout
    if ['small', 'wide'].include? params['layout']
      cookies.permanent['layout'] = params['layout']
    end

    @layout = cookies['layout']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    respond_to do |format|
      format.html { }
      format.json { render json: @user }
    end
  end

  def update
    if @user.update user_params
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :bio, :website, :cv
  end

  def set_user
    @user = User.find params[:id]
  end
end

app/views/home/index.html.erb
<% if current_user %>
  <% cache @current_user do %>
    <h1>Welcome</h1>
    <% if current_user.name.present? %>
      I really like your name, <%= current_user.name %>.
      <br />
    <% else %>
      I'm really sad. You don't have a name just yet. Please update your profile!
    <% end %>
  <% end %>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vulnerable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%== @layout %>">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Vulnerable', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'My profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit profile</h1>
<%= form_for @user, html: { multipart: true } do |f| %>
  <div class="form-group">
    <label for="user[name]">Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="user[website]">Website</label>
    <%= f.text_field :website, class: 'form-control' %>
    <span>Current: <%= link_to @user.website, @user.website %></span>
  </div>
  <div class="form-group">
    <label for="user[bio]">Bio</label>
    <%= f.text_field :bio, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="user[cv]">CV</label>
    <%= f.file_field :cv, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user %>
  <%= link_to 'Edit your profile', edit_user_path(@user) %>
  <br /><br />
<% end %>

<% if @user.name.present? %>
  Welcome, this is <%= @user.name %> its profile.
<% else %>
  This user hasn't provided a name yet, so there's not much to see here.
<% end %>

<br /><br />

<%= link_to @user.website, @user.website, target: '_blank' %>
<br />
<%= link_to 'Download CV', @user.cv.url %>